// 여기에 레스토랑 장소 200개 받아오는 함수를 만든다.

export const restaurantLists = [
  {
    restId: "1",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
  {
    restId: "2",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
  {
    restId: "3",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
  {
    restId: "4",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
  {
    restId: "5",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
  {
    restId: "6",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
  {
    restId: "7",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
  {
    restId: "8",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
  {
    restId: "9",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
  {
    restId: "10",
    name: "토리모리",
    x: 1,
    y: 2,
    miniStarUrl: "/Star_2.png",
    BigStarUrl: "/Star_3.png",
    FoodUrl: "/Food.png",
  },
];
